### ISSUE TITLE
Severe Viral Infection

### ISSUE THREAD

**Issue by Kittenayngel** [SirLich/sapiens-creative-mode#11] opened 2022-10-08 04:11 UTC
I tried your creative mode, and love it by the way. But when I went and invited three sapiens to the tribe they were miserable because they were starving, slept outside, were wet from rain, etc., so I clicked the little button to make them happy, they became happy but now they mysteriously have an extreme viral infection, which of course hit the whole tribe. Thanks to Decduck I found this site, so there, I told you! *chef's kiss* I have no idea how to drag and drop the files you will need, I only know how to type on the internet. So if you need a file you will have to explain how to find it. Love your mods! Nicolle (Kittenayngel on Discord)

**Comment by SirLich** [comment] 2022-10-08 13:04
This is caused by using `serverSapien:maxFollowerNeeds` which is used by Dave for testing purposes. It's not safe to call this. 

We need to replace this call with a copy of the function, where the testing code has been removed.

**Comment by death-rae** [comment] 2022-11-18 00:52
A fix for this issue (replacing maxFollowerNeeds with a custom function) is in my master branch now. After further testing, I will submit it to SirLich for review & merging.

**Closed** 2023-03-12 14:40 UTC
